bundler_args: --without yard guard benchmarks
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
script: "bundle exec rake ci"
rvm:
  - '2.1.6'
  - '2.2'
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head  # buggy with flay
    - rvm: ruby-head   # travis broken
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
sudo: false
