bundler_args: --without yard guard benchmarks
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
script: "bundle exec rake ci"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.8.7       # mutant fails
    - rvm: 1.9.3       # mutant fails
    - rvm: 2.0.0       # mutant fails
    - rvm: rbx-19mode  # mutant fails
    - rvm: ruby-head   # travis broken
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
