language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ree
    - rvm: 1.8.7
    - rvm: jruby-19mode
    - rvm: jruby-head
notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - dan.kubb@gmail.com
